services:
  pantry-db:
    container_name: pantry-db
    image: postgres
    environment:
      POSTGRES_DB: pantry-db
      POSTGRES_USER: pantry
      POSTGRES_PASSWORD: pantry
      PGDATA: /data/postgres
    volumes:
      - pantry-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - spring
    restart: always

  purchase-db:
    container_name: purchase-db
    image: postgres
    environment:
      POSTGRES_DB: purchase-db
      POSTGRES_USER: purchase
      POSTGRES_PASSWORD: purchase
      PGDATA: /data/postgres
    volumes:
      - purchase-db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
      - spring
    restart: always

  account-db:
    container_name: account-db
    image: postgres
    environment:
      POSTGRES_DB: account-db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: account
      PGDATA: /data/postgres
    volumes:
      - account-db:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
      - spring
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  kafka-broker:
    image: apache/kafka:3.7.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_LISTENERS: INTERNAL://kafka-broker:9092,CONTROLLER://kafka-broker:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kafka-logs
      KAFKA_LOG_RETENTION_HOURS: 2
      KAFKA_LOG_RETENTION_BYTES: 536870912  #536Mb
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_CLEANER_ENABLE: "true"
      KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - spring
    volumes:
      - kafka-data:/kafka-data
    restart: always

  pantry-service:
    image: fernandacastro/pantry-service:local
    build:
      context: pantry-service
      dockerfile: Dockerfile
    container_name: pantry-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SECURITY_SECRET=${SECURITY_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000
      - LOG_LEVEL=INFO
      - PARTITIONS=3
      - REPLICAS=2
    networks:
      - spring
      - postgres
    depends_on:
      - kafka-broker
      - pantry-db
    restart: always

  purchase-service:
    image: fernandacastro/purchase-service:local
    build:
      context: purchase-service
      dockerfile: Dockerfile
    container_name: purchase-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SECURITY_SECRET=${SECURITY_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000
      - LOG_LEVEL=INFO
      - PARTITIONS=3
      - REPLICAS=2
    networks:
      - spring
      - postgres
    depends_on:
      - kafka-broker
      - purchase-db
    restart: always

  redis-cache:
    container_name: redis-cache
    image: redis/redis-stack:7.4.0-v0
    volumes:
      - redis-cache:/local-data/:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - spring
    restart: always
    #Redis Insight exposed on port 8001

  account-service:
    image: fernandacastro/account-service:local
    build:
      context: account-service
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SECURITY_SECRET=${SECURITY_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000, http://localhost:8080, http://localhost:8081
      - LOG_LEVEL=INFO
    networks:
      - spring
      - postgres
    depends_on:
      - account-db
      - redis-cache
    restart: always

  pantry-web:
    container_name: pantry-web
    image: fernandacastro/pantry-web:local
    build:
      context: pantry-web
      dockerfile: Dockerfile
      args:
        API_URL_PANTRY: http://localhost:8080/pantryservice
        API_URL_PURCHASE: http://localhost:8081/purchaseservice
        API_URL_ACCOUNT: http://localhost:8082/accountservice
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "3000:3000"
    networks:
      - spring
    depends_on:
      - account-service
      - pantry-service
      - purchase-service
    restart: always

volumes:
  account-db:
  pantry-db:
  purchase-db:
  kafka-data:
  pgadmin:
  redis-cache:
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  kafka:
    driver: bridge