server:
  port: 8081
spring:
  application:
    name: purchase-service
  profiles:
    active: default
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/purchase-db
    username: purchase
    password: purchase
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
        mode: always