CREATE SCHEMA IF NOT EXISTS AUTHORIZATION purchase;
CREATE TABLE IF NOT EXISTS purchase.PURCHASE(
    ID BIGSERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP,
    PROCESSED_AT TIMESTAMP
);
CREATE TABLE IF NOT EXISTS purchase.PURCHASE_ITEM(
    ID BIGSERIAL PRIMARY KEY,
    PURCHASE_ID INT REFERENCES PURCHASE (ID),
    PANTRY_ID INT NOT NULL,
    PANTRY_NAME VARCHAR(30) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CODE VARCHAR(20) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(30) NOT NULL,
    PRODUCT_SIZE VARCHAR(10),
    QTY_PROVISIONED INTEGER,
    QTY_PURCHASED INTEGER
);
