CREATE SCHEMA IF NOT EXISTS AUTHORIZATION purchase;

CREATE TABLE IF NOT EXISTS purchase.PRODUCT(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    CODE VARCHAR(30) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(30),
    SIZE VARCHAR(10),
    CATEGORY VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS purchase.PURCHASE(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP,
    PROCESSED_AT TIMESTAMP
);
CREATE TABLE IF NOT EXISTS purchase.PURCHASE_ITEM(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    PURCHASE_ID INT REFERENCES PURCHASE (ID),
    PANTRY_ID INT NOT NULL,
    PANTRY_NAME VARCHAR(30) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QTY_PROVISIONED INTEGER,
    QTY_PURCHASED INTEGER
);

ALTER TABLE purchase.PURCHASE_ITEM DROP COLUMN IF EXISTS PRODUCT_CODE;
ALTER TABLE purchase.PURCHASE_ITEM DROP COLUMN IF EXISTS PRODUCT_DESCRIPTION;
ALTER TABLE purchase.PURCHASE_ITEM DROP COLUMN IF EXISTS PRODUCT_SIZE;
DROP SEQUENCE IF EXISTS PRODUCT_ID_SEQ CASCADE;

ALTER TABLE purchase.PURCHASE_ITEM DROP CONSTRAINT IF EXISTS PURCHASE_ITEM_PRODUCT_ID_FK;
ALTER TABLE purchase.PURCHASE_ITEM ADD CONSTRAINT PURCHASE_ITEM_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES purchase.PRODUCT (ID) NOT VALID;

CREATE TABLE IF NOT EXISTS purchase.PROPERTIES(
    PROPERTY_KEY VARCHAR(50)  PRIMARY KEY NOT NULL,
    PROPERTY_VALUE JSONB NOT NULL
);

--INSERT INTO properties values ('product.categories', '["HORTIFRUTI", "CARNES", "FRIOS", "LATICÍNEO", "PADARIA", "LIMPEZA", "HIGIENE PESSOAL", "MERCEARIA", "BEBIDAS"]');