CREATE SCHEMA IF NOT EXISTS AUTHORIZATION purchase;

CREATE TABLE IF NOT EXISTS purchase.PURCHASE(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP,
    PROCESSED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase.PURCHASE_ITEM(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    PURCHASE_ID SERIAL REFERENCES PURCHASE (ID),
    PANTRY_ID INT NOT NULL,
    PANTRY_NAME VARCHAR(30) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QTY_PROVISIONED INTEGER,
    QTY_PURCHASED INTEGER
);