CREATE TABLE IF NOT EXISTS purchase.PRODUCT(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    CODE VARCHAR(30) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(30),
    SIZE VARCHAR(10),
    CATEGORY VARCHAR(30)
);

DROP SEQUENCE IF EXISTS PRODUCT_ID_SEQ CASCADE;

ALTER TABLE purchase.PURCHASE_ITEM DROP COLUMN IF EXISTS PRODUCT_CODE;
ALTER TABLE purchase.PURCHASE_ITEM DROP COLUMN IF EXISTS PRODUCT_DESCRIPTION;
ALTER TABLE purchase.PURCHASE_ITEM DROP COLUMN IF EXISTS PRODUCT_SIZE;

ALTER TABLE purchase.PURCHASE_ITEM DROP CONSTRAINT IF EXISTS PURCHASE_ITEM_PRODUCT_ID_FK;
ALTER TABLE purchase.PURCHASE_ITEM ADD CONSTRAINT PURCHASE_ITEM_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES purchase.PRODUCT (ID); --NOT VALID


CREATE TABLE IF NOT EXISTS purchase.PROPERTIES(
    PROPERTY_KEY VARCHAR(50)  PRIMARY KEY NOT NULL,
    PROPERTY_VALUE JSONB NOT NULL
);

INSERT INTO PROPERTIES VALUES
('product.categories', '["", "Bakery", "Beverages", "Cleaning", "Coockies", "Dairy", "Frozen", "Fruit and vegetables", "Grocery", "Meat", "Personal Hygiene", "Refrigerated"]');