server:
  port: 8080
kafka-config:
  bootstrap-servers-config: kafka-broker:9092
  purchase-create-topic: purchaseCreateTopic
  purchase-complete-topic: purchaseCompleteTopic
  product-topic: productTopic
  pantry-group: pantryGroup
spring:
  application:
    name: pantry-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://pantry-db:5432/pantry-db
    username: pantry
    password: pantry
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  flyway:
    baselineOnMigrate: true  #Needed when schema is not empty
    baselineVersion: 0
    encoding: ISO-8859-1
management:
  endpoints:
    web:
      exposure:
        include: health
security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin: ${ALLOWED_ORIGINS}
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
  authzServer: http://account-service:8082
  https: true
logging:
  level:
    root: ${LOG_LEVEL}
    org.hibernate.SQL: ${LOG_LEVEL}
    org.springframework.web: ${LOG_LEVEL}
    og.springframework.security: ${LOG_LEVEL}