server:
  port: 8080
kafka-config:
  bootstrap-servers-config: localhost:9092
  purchase-create-topic: purchaseCreateTopic
  purchase-complete-topic: purchaseCompleteTopic
  product-topic: productTopic
  group: pantryGroup
  partitions: 3
  replicas: 2
spring:
  application:
    name: pantry-service
  profiles:
    active: default
  datasource:
    platform: postgres
    url: jdbc:postgresql://m1r.h.filess.io:5433/pantrydb_showfinal
    username: pantrydb_showfinal
    password: 292faeaadf4439e6c5e2d27a26699a0a9f7e1fe1
    schema: pantry
    hikari:
      minimum-idle: 1
      maximum-pool-size: 4
    #    url: jdbc:postgresql://localhost:5432/pantry-db
    #    username: pantry
    #    password: pantry
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: pantry
  sql:
    init:
        mode: always
  flyway:
    baselineOnMigrate: true  #Needed when schema is not empty
    defaultSchema: pantry
    baselineVersion: 0
    encoding: ISO-8859-1
management:
  endpoints:
    web:
      exposure:
        include: health
security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin:
    - http://localhost:3000
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
  authzServer: http://localhost:8082
logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.springframework.web: INFO
    og.springframework.security: INFO
