server:
  port: 8080
spring:
  application:
    name: pantry-service
  profiles:
    active: default
  config:
    import: optional:file:.dev.env[.properties]
  datasource:
    platform: postgres
    url: ${PANTRY_DB_URL:jdbc:postgresql://localhost:5432/pantry-db}
    username: ${PANTRY_DB_USERNAME:pantry}
    password: ${PANTRY_DB_PASSWORD:pantry}
    schema: pantry
    hikari:
      minimum-idle: ${PANTRY_DB_IDLE_CONN:1}
      maximum-poolsize: ${PANTRY_DB_MAX_POOL_SIZE:2}
      idle-timeout: ${PANTRY_DB_IDLE_TIMEOUT:60000}
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: pantry
  sql:
    init:
        mode: always
  flyway:
    baselineOnMigrate: ${PANTRY_SCHEMA_EXISTS:false}  #Set to true when schema is not empty
    baselineVersion: 0
    encoding: ISO-8859-1
    defaultSchema: pantry
kafka-config:
  bootstrap-servers-config: localhost:29092
  purchase-create-topic: purchaseCreateTopic
  purchase-complete-topic: purchaseCompleteTopic
  product-topic: productTopic
  group: pantryGroup
  partitions: ${PARTITIONS:1}
  replicas: ${REPLICAS:1}
security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin: ${ALLOWED_ORIGINS:http://localhost:3000}
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
  authzServer: ${AUTHZ_SERVER:http://localhost:8082}
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_WEB_EXPOSURE:health}
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${HIBERNATE_LOG_LEVEL:OFF}
    org.springframework.web: ${WEB_LOG_LEVEL:ERROR}
    org.springframework.security: ${SECURITY_LOG_LEVEL:ERROR}
