INSERT INTO PRODUCT (CODE, DESCRIPTION, UNIT, AMOUNT) VALUES ('CREME_LEITE', 'Sahne zum Kochen', 'CX', '200g') ON CONFLICT(CODE) DO NOTHING;
INSERT INTO PANTRY (NAME, TYPE, ACTIVE) VALUES ('DESPENSA BASE', 'R', TRUE) ON CONFLICT(NAME) DO NOTHING;
INSERT INTO PANTRY_PRODUCT (PANTRY_ID, PRODUCT_ID, IDEAL_QUANTITY, CURRENT_QUANTITY) VALUES (1, 1, 5, 5) ON CONFLICT(PANTRY_ID, PRODUCT_ID) DO NOTHING