CREATE SCHEMA IF NOT EXISTS AUTHORIZATION pantry;
CREATE TABLE IF NOT EXISTS pantry.PRODUCT(
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(30) NOT NULL,
    UNIT VARCHAR(10),
    AMOUNT VARCHAR(10)
);
CREATE TABLE IF NOT EXISTS pantry.PANTRY(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL UNIQUE,
    TYPE CHAR(1),
    ACTIVE BOOLEAN
);
CREATE TABLE IF NOT EXISTS pantry.PANTRY_PRODUCT(
    PANTRY_ID BIGSERIAL NOT NULL REFERENCES PANTRY (ID),
    PRODUCT_ID BIGSERIAL NOT NULL REFERENCES PRODUCT (ID),
    IDEAL_QTY INTEGER,
    CURRENT_QTY INTEGER,

    CONSTRAINT PANTRY_PRODUCT_UNIQUE UNIQUE ( PANTRY_ID, PRODUCT_ID )
);
