server:
  port: 8082
spring:
  application:
    name: account-service
  profiles:
    active: default
  datasource:
    platform: postgres
    #    url: jdbc:postgresql://m1r.h.filess.io:5433/pantrydb_showfinal
    #    username: pantrydb_showfinal
    #    password: 292faeaadf4439e6c5e2d27a26699a0a9f7e1fe1
    #    schema: account
    #    hikari:
    #      minimum-idle: 1
    #      maximum-pool-size: 1
    url: jdbc:postgresql://localhost:5434/account-db
    username: account
    password: account
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: account
  sql:
    init:
        mode: always
  flyway:
    baselineOnMigrate: true
    defaultSchema: account
    baselineVersion: 0
    encoding: ISO-8859-1
management:
  endpoints:
    web:
      exposure:
        include: health
security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin:
    - http://localhost:3000
    - http://localhost:8080
    - http://localhost:8081
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.springframework.web: INFO
    og.springframework.security: INFO



