server:
  port: 8082
spring:
  application:
    name: account-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://account-db:5432/account-db
    username: account
    password: account
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
        mode: always
  flyway:
    baselineOnMigrate: true
     baselineVersion: 0
    encoding: ISO-8859-1
security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin:
    - http://localhost:3000
    - http://localhost:8081
    - http://localhost:8081
    - http://castrolecar:3000
    - http://castrolecar.local:3000
    - http://castrolecar.netbird.cloud:3000
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
  accessControlDomains:
    - http://pantry-service:8080
    - http://purchase-service:8081