server:
  port: 8082
spring:
  application:
    name: account-service
  profiles:
    active: default
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/account-db
    username: account
    password: account
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
        mode: always
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 30000
      repositories:
        enabled: false
  cache:
    type: redis
  flyway:
    baselineOnMigrate: true   #Needed when schema is not empty
    baselineVersion: 0
    encoding: ISO-8859-1
management:
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      enable:
        all: true
security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin:
    - http://localhost:3000
    - http://localhost:8080
    - http://localhost:8081
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
cache-config:
  role-ttl: 5
  members-ttl: 5
  acl-ttl: 5
logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cache: DEBUG



