server:
  port: 8082
spring:
  application:
    name: account-service
  datasource:
    platform: postgres
    url: ${ACCOUNT-DB-URL}
    username: ${ACCOUNT_DB_USERNAME}
    password: ${ACCOUNT-DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
        mode: always
  redis:
    host: ${REDIS-HOST}
    port: ${REDIS-PORT}
  cache:
    type: redis
  flyway:
    baselineOnMigrate: true
    baselineVersion: 0
    encoding: ISO-8859-1
management:
  endpoints:
    web:
      exposure:
        include: health
security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin: ${ALLOWED_ORIGINS}
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
logging:
  level:
    root: ${LOG_LEVEL}
    org.hibernate.SQL: ${LOG_LEVEL}
    org.springframework.web: ${LOG_LEVEL}
    og.springframework.security: ${LOG_LEVEL}