CREATE SCHEMA IF NOT EXISTS AUTHORIZATION account;

CREATE TABLE IF NOT EXISTS account.ACCOUNT(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    NAME VARCHAR(50),
    EXTERNAL_PROVIDER VARCHAR(30),
    PICTURE_URL VARCHAR(100),
    PASSWORD VARCHAR(80),
    PASSWORD_QUESTION VARCHAR(100),
    PASSWORD_ANSWER VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS account.ACCOUNT_GROUP(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    PARENT_ACCOUNT_GROUP_ID BIGINT REFERENCES ACCOUNT_GROUP (ID),
    NAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS account.ACCOUNT_GROUP_MEMBER(
    ACCOUNT_GROUP_ID BIGINT NOT NULL REFERENCES ACCOUNT_GROUP (ID),
    ACCOUNT_ID BIGINT NOT NULL REFERENCES ACCOUNT (ID),
    ROLE VARCHAR(30) NOT NULL
);




