name: Build and Publish pantry-service

on:
  pull_request:
    types:
      - closed
    paths:
      - 'pantry-service/**'
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SECURITY_SECRET: ${{ secrets.SECURITY_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
    steps:
      - name: Variables in use
        run: |
          echo ALLOWED_ORIGINS = $ALLOWED_ORIGINS

      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish with Maven
        run: mvn clean package -pl pantry-service -am -P 'build-publish-image'