name: Deploy pantry-web to S3

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    paths:
      - 'pantry-web/**'
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build
        env:
          REACT_API_URL_PANTRY: ${{ vars.PROD_API_URL_PANTRY }}
          REACT_API_URL_PURCHASE: ${{ vars.PROD_API_URL_PURCHASE }}
          REACT_API_URL_ACCOUNT: ${{ vars.PROD_API_URL_ACCOUNT }}
          REACT_GOOGLE_CLIENT_ID: ${{ secrets.PROD_GOOGLE_CLIENT_ID }}
        
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          npm install -g aws-cli
          aws s3 sync build/ s3://mypantry-web --delete
